person = ("Jane", 25, "Python Developer", "Canada")
print(person) # tuples are immutable , cannot modify later
print(type(person))
per=()
print(per)
per2=(1)
print(per2)
print(type(per2))
tup=(1,2,3,4,2)
print(tup[1:3])
print(tup.index(2))
print(tup.count(2))
